### ISSUE TITLE
Slush generator?

### ISSUE THREAD

**Issue by kokujin** [arvindr21/myRESTApp#1]
Would this get a slush generator? :)

**Comment by arvindr21** [comment]
@kokujin What exactly are you looking for in the generator? If you want it to download the resources in this repo, with out any options, I would suggest `git clone ...`,

**Comment by kokujin** [comment]
@arvindr21  I like the app structure and the fact that it uses JWT. It's ok, I'll stick with your slush generator and tack the JWT support on then. Thanks

**Comment by arvindr21** [comment]
Okay.. Cool.
