### ISSUE TITLE
Need some help, can't get token

### ISSUE THREAD

**Issue by ytian90** [arvindr21/myRESTApp#5]
Hi,

When I use
curl –data “{\”username\” : \”arvind@myapp.com\”, \”password\” : \”pass123\”}” -H “content-type:application/json” http://localhost:3000/login
Error occurs
curl: (6) Could not resolve host: –data
curl: (3) [globbing] unmatched brace in column 4
curl: (7) Failed to connect to  port 80: Connection refused
curl: (6) Could not resolve host: myapp.com”,
curl: (6) Could not resolve host: ”password”
curl: (7) Failed to connect to  port 80: Connection refused
curl: (3) [globbing] unmatched close brace/bracket in column 14
curl: (52) Empty reply from server

What should I do for it.
Thanks!!

**Comment by LeoPenaguin** [comment]
Hi @ytian90 you posted your issue a moment ago, have you solved the problem ? I still don't understand why this route in particular doesn't work :/

**Comment by LeoPenaguin** [comment]
FYI (15 minutes later :D) I tried with postman by putting the _"{"username" : "arvind@myapp.com", "password" : "pass123"}"_ json/string as raw is the request body and it gave me a token :)

I still don't understand why it didn't work with CURL :o

**Comment by arvindr21** [comment]
The problem I feel is the quotes. When you copy them off the browser they sometimes go crazy 🤪

Copy the same command in cUrl delete and retype the double quotes in the same place. 

Also the flag is `--data`, I can see only one. 

Should work!

**Comment by LeoPenaguin** [comment]
Yes ! Worked :) Thanks a lot (and thanks for the great post)

**Comment by arvindr21** [comment]
Great!
